"""books table remove uniqute in path

Revision ID: 3b6062641ca3
Revises: 9e9e5d591e10
Create Date: 2023-08-20 19:27:28.830223

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b6062641ca3'
down_revision: Union[str, None] = '9e9e5d591e10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('cover_image', table_name='books')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('cover_image', 'books', ['cover_image'], unique=False)
    # ### end Alembic commands ###
